// Hand-curated release log. Single source of truth for the version
// label in the footer and the changelog modal that opens when you
// click it. Bump the top entry on every meaningful push.
//
// Versioning policy (loose semver — internal app, no API contract):
//   MAJOR — architectural shift (auth model, role overhaul, new core
//           surface like Player pages or the Requests detail panel)
//   MINOR — meaningful new feature, template, or workflow
//   PATCH — polish, fixes, perf, copy
//
// `kind` drives the chip color in the modal. Newest entry first.
// Items use plain Markdown-flavored prose — no HTML, the modal renders
// them as a bulleted list.
//
// CURRENT_VERSION below auto-derives from the first entry, so the only
// thing you need to edit when shipping is this array (add a new
// release object at the top).

export const RELEASES = [
  {
    version: '4.5.63',
    date: '2026-05-14',
    kind: 'minor',
    summary: 'v4.6 prep wave C-1: Requests + Studio quality of life',
    items: [
      'Studio: Templates that need an overlay but have none uploaded for the active team are now greyed out in the picker with a NO OVERLAY chip. Clicking shows a toast pointing the user to the upload affordance instead of silently dropping them into a template that\'ll render the raw photo + text. Blank Slate and Stat Card stay clickable since they own their own chrome.',
      'Studio: new "Stat card only" export button (2× transparent PNG). Renders just the card with no background photo, sized exactly to the card\'s own box. Drop straight into Premiere, Keynote, video composites, etc.',
      'Requests: master_admin can now permanently remove a request (🗑 Remove button on every row). Confirms before deleting; the row is filtered from local state and cloud-sync pushes the delete on next flush.',
      'Requests: Deny button on every pending row. Prompts for a reason, captures it as a comment so the queue shows WHY it was declined, flips status to "declined", and pre-fills a mailto: with the reason so the requester gets the explanation directly. Non-master staff can deny too; only master can fully remove.',
      'Dashboard: clicking a Recent Posts tile now opens a full-size LIGHTBOX preview of the rendered PNG instead of bouncing to Studio. Re-edit is still one click away via "✎ Open in Studio" inside the lightbox actions slot — it\'s just no longer the default click target.',
    ],
  },
  {
    version: '4.5.62',
    date: '2026-05-14',
    kind: 'patch',
    summary: 'v4.6 prep wave B: Studio template defaults + layout',
    items: [
      'Studio: Format dropdown removed. Every BLW post now exports at 1080×1350 portrait (the IG feed format master is standardizing on). Saves a click + eliminates off-brand exports.',
      'Studio: Template picker moved BELOW Player in the form flow (pick team + player first, THEN pick what to make). Thumbnails shrunk 72px→48px so the strip doesn\'t dominate the column. No longer floats above the preview area.',
      'Team/Player News template: default Y coordinates updated to 1018 / 1151 / 1288 per design call. Font stays Press Gothic 120pt, X stays 540.',
      'Team/Player News + Hype/Promo: X-axis is now LOCKED at 540 across all content lines. Saved field-overrides can drift Y / font / size / color but the horizontal anchor stays put so lines stay centered against the chyron.',
      'Team/Player News: Zoom slider can now go as low as 0.50× (was 1.00× minimum) so landscape source photos can letterbox-fit inside the portrait canvas without losing the sides. Other templates stay clamped to ≥1.00× because letterboxing them looks broken.',
      'Suggested stat lines: number-first format per master direction. "OPS+ 117 · 0.890 OPS" → "117 OPS+ · 0.890 OPS". Same for power / advanced / dominance / strikeout variants and the placeholder template.',
    ],
  },
  {
    version: '4.5.61',
    date: '2026-05-14',
    kind: 'patch',
    summary: 'v4.6 prep wave A: UX cleanup + copy polish',
    items: [
      'Sidebar/header: removed the static bell icon — it was never wired up to anything and just took header space.',
      'Effects: removed Top Fade preset (Bottom Fade + Team Fade cover the same intent without shadowing the headline area).',
      'Studio: stat-card and blank-slate templates now default to text VISIBLE instead of hidden. Hype/Promo stays text-off so the cinematic image isn\'t covered on first paint.',
      'Studio: Overlay section is no longer shown on stat-card or blank-slate. Stat cards have their own chrome; blank-slate is meant to ship a clean canvas. Putting an overlay on either was always a foot-gun.',
      'Studio: removed the 120px-tall "current selection" thumbnail above the player-media grid — it duplicated the live preview. The selected tile is highlighted in the grid; Clear sits inline with the grid header.',
      'Studio: Headline picker now only offers OFF + Winner Sans. The other display faces produced inconsistent brand expression. Pill is also 15% tighter against the text and corners are pulled in further (radius 18%→10% capped at 14px) so it reads as a chip, not a capsule.',
      'Requests modal: Team dropdown gains "League-wide (BLW)" option for content that isn\'t tied to a single team. Player dropdown gains "Any player" option for cross-roster requests (all-star recaps, etc).',
      'Requests modal: removed the per-content "Athlete\'s input (optional)" textarea — it duplicated the universal description box at the bottom and athletes were filling out both with the same content.',
      'Files: keyword search now does multi-token AND match across name + team + player + asset type. "jaso headshot", "lan hype", "jeter ace" all match the intuitive results — pre-fix the prefix-substring on filename missed most of them.',
      'Files: Drive folder panels default to collapsed so a long list doesn\'t dominate the page on first paint. Existing rename UI is still there for labeling them ("LAN headshots", "Spring training group shots") so the whole team can find contents at a glance.',
      'Photo lightbox (Files, BulkImport, Team page, Player page): clicking ANYWHERE outside the photo now closes — previously the close handler required clicking the exact backdrop element, so the dim area around the image felt unclickable. ESC still works.',
    ],
  },
  {
    version: '4.5.60',
    date: '2026-05-13',
    kind: 'minor',
    summary: 'Click any photo tile to preview at full size',
    items: [
      'Every photo grid now opens a full-size lightbox on click — Team Photos and Recent Player Media on the team page, plus every grouped gallery (HEADSHOT / PORTRAIT / HITTING / etc.) on the player page. Hover state shows a slight lift + shadow + `zoom-in` cursor so the affordance reads visually.',
      'Arrow-key nav between photos, ESC to close, click-outside-to-close. The lightbox uses the original full-resolution blob from IndexedDB rather than the compressed thumbnail, so the preview reads the same as the actual stored file.',
      'Built on a tiny new hook (usePhotoLightbox) next to PreviewLightbox so the same one-liner wires up any future photo grid: drop the hook in, pipe (items, index) into openAt, render <PreviewLightbox {...lightboxProps}> at the bottom.',
      'Files page + bulk import modal already had this — TeamPage and PlayerPage were the obvious gaps.',
    ],
  },
  {
    version: '4.5.59',
    date: '2026-05-13',
    kind: 'patch',
    summary: 'Hotfix: Studio media picker leaked across cross-team cousins',
    items: [
      'Reported symptom: selecting Connor Smith (SDO) in Studio surfaced Cam Smith (MIA) photos in the media picker. Same bug on the player-page gallery.',
      'Root cause: findPlayerMedia matched by lastname across ALL teams (intentional, so traded players keep their media history), then disambiguated by first-initial and jersey number. When a cross-team cousin shared BOTH lastname and FI — Cam vs Connor Smith — any photo missing an explicit jersey number tag leaked through (untagged-num records pass the disambiguation filter by design). Cam\'s legacy MIA uploads were the culprit.',
      'Fix: when same-team matches exist after the FI/num filter, drop the cross-team records entirely — mirrors the same-team-first pool restriction in resolvePlayerAvatar. Traded players still get their old-team photos because the fallback kicks in only when zero same-team matches survive.',
      'Affects both Studio (Generate page media picker) and PlayerPage gallery — both call findPlayerMedia.',
    ],
  },
  {
    version: '4.5.58',
    date: '2026-05-13',
    kind: 'patch',
    summary: 'Percentile cards: tighter rows, beefier stat numbers',
    items: [
      'Percentile card heights trimmed ~13% across every platform (feed 540→470, portrait 580→505, story 640→555, landscape 540→470). Rows were over-spaced for the 9-stat density and gave the card a stretched feel; pulling the body in makes each row more dense without losing readability.',
      'Stat-number font multiplier bumped 0.36 → 0.44 of row height, and bar thickness 0.40 → 0.42. The labels on the left and the actual stat values on the right (the numbers flanking the percentile bubble) now read as the dominant element of each row instead of getting outshouted by the bubble.',
      'Raw stat-card heights unchanged — the issue was specific to the 9-row percentile cards.',
    ],
  },
  {
    version: '4.5.57',
    date: '2026-05-13',
    kind: 'patch',
    summary: 'Hotfix: cousin pairs shared a roster avatar on team pages',
    items: [
      'Reported symptom: on the Dallas Pandas team page, Logan Rose (#08) and Luke Rose (#05) showed the SAME headshot on their roster cards, even though clicking through to each player\'s page rendered the right photo for each.',
      'Root cause: TeamPage stored resolved avatars in a Map keyed by `${firstInitial}|${lastName}` — so both Roses produced "L|ROSE" and the second cousin\'s avatar silently clobbered the first. The avatar resolver was actually doing its job correctly (it returned Logan\'s PORTRAIT and Luke\'s HEADSHOT separately); the storage layer is what threw one of them away.',
      'Fix: keyed by playerSlug (e.g. "logan-rose" vs "luke-rose") at both the write site (the for-loop building the avatar map) and the read site (the roster-card render). Same bug surface for any other cousin pair sharing first initial — James/Justin Lee on LV, etc. Verified live on DAL.',
    ],
  },
  {
    version: '4.5.56',
    date: '2026-05-13',
    kind: 'patch',
    summary: 'Portal every remaining modal (defense-in-depth)',
    items: [
      'Follow-up to the v4.5.55 BulkImportModal fix. Audited every modal in the app and applied the createPortal-to-body pattern to the four that were still rendering inside the .route-enter wrapper: RequestModal (new content/profile/bug requests), ChangelogModal (release notes from the sidebar footer), InviteModal in PeopleAdmin (master inviting a new user), and QuickSwitcher (Cmd-K).',
      'QuickSwitcher and ChangelogModal mount outside .route-enter at App root so they never actually hit the bug — but uniform pattern means the next teammate adding a modal doesn\'t have to remember which side of the route wrapper they\'re on.',
      'Visual behavior is unchanged. The only thing portaling does is anchor position:fixed to the viewport instead of the nearest transformed ancestor.',
    ],
  },
  {
    version: '4.5.55',
    date: '2026-05-13',
    kind: 'patch',
    summary: 'Hotfix: bulk import modal opened off-screen',
    items: [
      'Reported symptom: clicking "📁 Bulk import folder" on Files appeared to do nothing — no modal, no console error. The screen barely dimmed and that was it.',
      'Root cause: the route-change fade-in (.route-enter on the page wrapper in App.jsx) keeps an identity transform applied via `animation-fill-mode: both`. Any descendant with `position: fixed` ends up anchored to that wrapper instead of the viewport, so the modal\'s `inset: 0` backdrop expanded to ~18,000px (the full scroll height of the Files page) and the centered Card landed ~9,000px below the viewport — visible only if you scrolled the body. Same browser quirk that bit PlayerPage modals last year, fixed there with createPortal.',
      'Fix: BulkImportModal now portals to document.body, sidestepping the .route-enter containing-block entirely. Audited every other modal — request-modal, changelog-modal, PeopleAdmin user-edit, and quick-switcher — and flagged the ones that need the same treatment for follow-up if they ever start misbehaving.',
    ],
  },
  {
    version: '4.5.54',
    date: '2026-05-06',
    kind: 'patch',
    summary: 'Studio downloads always save as .png (Safari blob fix)',
    items: [
      'Reported symptom: a downloaded file occasionally showed up without a .png extension (e.g., "0526 POST 2.2") and macOS treated it as a generic document instead of an image. The file WAS valid PNG data — Safari just dropped the extension during download.',
      'Root cause: link.href = canvas.toDataURL(\'image/png\') hits a hard cap in Safari (~4 MB of base64). When the data URL exceeded the cap — common on 2× HD exports of full-resolution photos — Safari silently fell back to "open in new tab" and the OS-suggested filename lost the .png.',
      'Fix: switched the download path to canvas.toBlob + URL.createObjectURL. Blob URLs have no size cap and every browser honors the download attribute reliably, so the filename ends in .png every time. Object URL gets revoked 1 second after click to leave Safari time to read the blob on slower disks.',
      'Also defensive: every dot in the filename body now becomes a dash, so a player name like "J.J. Smith" or any caption with internal dots can\'t accidentally fool the OS into parsing the wrong segment as the extension.',
    ],
  },
  {
    version: '4.5.53',
    date: '2026-05-06',
    kind: 'patch',
    summary: 'Bulk importer: per-file cloud-sync visibility + retry',
    items: [
      'saveMedia now AWAITS the cloud sync inline and stamps cloudSyncedAt (or cloudSyncError) on every record before returning. Mirrors the v4.5.46 fix for overlays/effects. Pre-fix, fire-and-forget cloud sync silently dropped failures so a 50-file bulk import could leave a dozen records stuck local-only with no UI signal.',
      'Bulk importer Done screen now shows the actual cloud-sync split: "✓ All 50 synced to cloud" (green) or "30 synced · 20 stuck local-only" (amber). Lists the first three error reasons inline so you can tell at a glance whether it\'s a payload-too-large issue, an auth issue, or a transient network blip.',
      'New resyncMedia(id) and resyncAllLocalOnlyMedia() helpers — same shape as the overlay equivalents — for retrying stuck media records.',
      'Cloud-pulled records get cloudSyncedAt stamped at row→record conversion so other devices\' UI doesn\'t flag them as local-only.',
    ],
  },
  {
    version: '4.5.52',
    date: '2026-05-06',
    kind: 'patch',
    summary: 'Hotfix: AI endpoints (ideas/captions/auto-tag) were 401-ing',
    items: [
      'v4.5.37 added requireUser() to /api/ideas, /api/captions, and /api/auto-tag — but the FIVE client callsites were still using plain fetch() without the Authorization header. Every AI call (idea generation, caption drafts, auto-tag) has been silently 401-ing since v4.5.37 shipped.',
      'All callsites now use authedFetch which attaches the Supabase session JWT: src/auto-tag-api.js (1 site), src/idea-card.jsx (2 sites — draft + regenerate), src/pages/ContentStudio.jsx (1 site), src/pages/PlayerPage.jsx (1 site).',
      'AI features should work end-to-end immediately on next page load.',
    ],
  },
  {
    version: '4.5.51',
    date: '2026-05-06',
    kind: 'patch',
    summary: 'Hotfix: invitation links hung on "Signing you in…"',
    items: [
      'v4.5.45 switched the auth flow to PKCE to defeat email-scanner token-burn. PKCE works for return-user sign-ins (where the same browser stored a code_verifier) but BREAKS invitation links — invited users have no prior signInWithOtp call, so the SDK\'s auto-exchange found no code_verifier and hung indefinitely on the "Signing you in…" spinner. lrose@blwwiffleball.com was the canary.',
      'AuthCallback now explicitly handles invitation/recovery/email-change links by detecting `?token_hash=&type=` in the URL and calling supabase.auth.verifyOtp({ token_hash, type }) directly. The auto-exchange path (PKCE `?code=` for returning users) is unchanged.',
      '12-second escape hatch: if the page is still loading with no user and no error after 12 seconds, the spinner swaps for a "This is taking too long — send a new link" recovery CTA. Guarantees no user gets stuck on the spinner indefinitely.',
    ],
  },
  {
    version: '4.5.50',
    date: '2026-05-06',
    kind: 'patch',
    summary: 'Stat-card headers: re-center raw, drop logo from percentile',
    items: [
      'Raw stat cards: title is now centered across the full card width again. v4.5.48 left-shifted it to make room for the prowiffleball wordmark; the wordmark sits hard right and the title visually clears it on every platform export size, so the offset wasn\'t necessary.',
      'Percentile cards: prowiffleball wordmark removed entirely. The long title ("BLW PITCHING PERCENTILE RANKINGS") needs the full header width — adding a logo overlapped the text. Raw cards keep the wordmark since their title is short and there\'s natural empty space on the right.',
    ],
  },
  {
    version: '4.5.49',
    date: '2026-05-06',
    kind: 'minor',
    summary: 'Cross-device hydration — close the local/cloud gap',
    items: [
      'Bug: refreshFromCloud silently dropped any record whose blob fetch failed during hydration. The cloud row existed but the local IDB had no entry — getAllMedia() under-reported by however many blobs the network couldn\'t reach. Result: signing into a fresh device showed 188/340 files; another device showed 256/340. Fixed by ALWAYS writing the metadata row to IDB; missing blobs are flagged with cloudBlobMissing: true so the UI can surface a retry.',
      'Hydrate now downloads blobs in parallel batches of 8 instead of sequentially. A 340-blob hydrate at sequential speeds took ~70s — long enough for users to navigate away and leave a partial state. Concurrency 8 finishes the same hydrate in under 10s on a normal connection.',
      'New gap banner on the Files page: when local IDB count < cloud media count, a yellow callout shows "N files in cloud not yet on this device · Local 256 · Cloud 340" with a one-click "↻ Sync N from cloud" button. Newly-signed-in admins see exactly what to do, no scrolling required.',
      'Refresh report rewritten to show the actual gap: "Media: 340 records · +84 new blobs · 12 still missing" with a hint to retry. Replaces the old "Media +0" message that hid silent failures.',
      'Same fixes apply to overlay + effect hydration (same hydrateBlobKind path).',
    ],
  },
  {
    version: '4.5.48',
    date: '2026-05-06',
    kind: 'patch',
    summary: 'prowiffleball.com wordmark on stat-card headers',
    items: [
      'Raw stat cards (Hitting Stats / Pitching Stats): white prowiffleball.com wordmark now sits on the right side of the team-color gradient header. Title shifts to balance against the reserved logo zone so the composition still reads centered.',
      'Percentile cards (Hitting Percentiles / Pitching Percentiles): dark prowiffleball.com wordmark on the right side of the white header. Canvas globalCompositeOperation re-fills the white SVG\'s alpha shape with navy on the fly; cached so subsequent renders are zero-cost.',
      'Logo loads asynchronously at module init; Studio waits for the load to resolve before the first stat-card paint so the logo never pops in on user interaction.',
    ],
  },
  {
    version: '4.5.47',
    date: '2026-05-06',
    kind: 'patch',
    summary: 'ProWiffle Stats page header credits prowiffleball.com',
    items: [
      'Page header rewritten from "PROWIFFLE STATS · Stats, rankings, and standings from Grand Slam Systems" → "BLW STATISTICS BY PROWIFFLEBALL.COM" with the wordmark inline as a clickable link.',
      'New supporting copy: explains what readers get on this page (standings, rankings, basic hitting/pitching for active rostered players) and points them to prowiffleball.com for box scores + detailed stats.',
      'Added a second paragraph linking to prowiffleball.com/rankings/fast-pitch — explains how Grand Slam Systems curates OPWB® Rankings via "clicking here" hyperlink.',
    ],
  },
  {
    version: '4.5.46',
    date: '2026-05-06',
    kind: 'minor',
    summary: 'Overlay cloud-sync visibility — per-overlay status + retry',
    items: [
      'Overlay (and effect) saves now AWAIT the cloud sync inline instead of fire-and-forget. The record carries cloudSyncedAt + cloudSyncError so the picker can render exactly what made it to other admins vs. what\'s stuck on this machine.',
      'Picker tiles get a per-overlay indicator dot — green ✓ when in cloud, amber ↻ when local-only. Click the amber dot to retry that ONE overlay without redoing the whole batch. Local-only tiles also get an amber rim so the eye lands on them.',
      'Picker header shows "N LOCAL-ONLY" badge + "↻ Sync local-only (N)" button when any overlay didn\'t make it. Bulk retry walks the list sequentially so a flaky network on one doesn\'t take down the rest.',
      'Upload toast now reports the actual cloud-sync split — "X synced · Y stuck local-only" — instead of a blanket "saved!" that hid silent failures. Single-file uploads also surface the specific error in the toast detail.',
      'Cloud-pulled overlays get cloudSyncedAt stamped automatically (they\'re by definition in the cloud), so the indicator only fires for genuine local-only records.',
      'Same treatment for the Effects store — saveEffect / resyncEffect / resyncAllLocalOnlyEffects mirror the overlay path.',
    ],
  },
  {
    version: '4.5.45',
    date: '2026-05-06',
    kind: 'patch',
    summary: 'Magic links now survive corporate email scanners (PKCE)',
    items: [
      'Auth flow switched implicit → PKCE. Magic links no longer carry the access token directly — instead they carry a `?code=` that\'s only redeemable with a `code_verifier` stored in the user\'s browser. Defeats Outlook 365 / Mimecast / Barracuda email security tools that pre-click every URL in inbound email and were burning the one-time token before users could click. Side effect: returning sign-in links must be opened on the same device/browser they were requested from (almost always the case in practice).',
      'AuthCallback error state now explains why a "expired/invalid" link likely happened (corporate scanner pre-clicked it OR opened on a different device) and offers a one-click "Send a new link" CTA so the user can self-recover instead of contacting the admin.',
      'Master-admin pre-flight checklist updated with email-scanner guidance: tell invitees to click within 30 minutes, not forward the email, and not let their email client "preview" the link.',
    ],
  },
  {
    version: '4.5.44',
    date: '2026-05-05',
    kind: 'minor',
    summary: 'Sticky preview + Headline on every template + Teams icon',
    items: [
      'Teams sidebar icon swapped 🏟 → 🚩 (Triangular Flag, Unicode 6.0/2010). The stadium emoji from v4.5.39 was Unicode 8.0 (2015) and still missing from older system emoji fonts on iOS 9 / macOS 10.10 — flag is universal across every emoji font shipped in the last 15 years.',
      'Headline pill now available on every template EXCEPT Team/Player News (player-stat). News intentionally uses three matched stacked lines — wrapping one in a pill would break the symmetric typographic stack. Game Day, Final Score, Hype/Promo, Highlight, Stat Leader, Player of the Game, Standings, Blank Slate, and Stat Card all now show the headline picker.',
      'Studio preview is now sticky on desktop — the canvas + download buttons stay pinned at the top of the right column while you scroll the controls. No more "scroll up to confirm, scroll down to edit" loop. Download row moved into the sticky panel so it\'s one click away from any scroll position. maxHeight + overflowY means tall right columns (canvas + Photo Adjust + download) scroll internally without forcing the page to grow.',
    ],
  },
  {
    version: '4.5.43',
    date: '2026-05-05',
    kind: 'patch',
    summary: 'Headline pill: per-font centering + softer corners',
    items: [
      'Pill now centers on the actually-rendered glyphs via ctx.measureText().actualBoundingBoxAscent/Descent — adapts to whatever font the picker selected (winner / heading / press / united / gotham / condensed) instead of a one-size-fits-all 0.78×fontSize approximation. Winner Sans no longer renders bottom-heavy.',
      'Corner radius is now 18% of pill height capped at 24px — was pillH/2.6 (a near-capsule). Reads as a softly-rounded rectangle that sits with the rest of the BLW chrome.',
      'Vertical padding bumped 0.18 → 0.22×fontSize for a touch more breathing room above and below the headline.',
    ],
  },
  {
    version: '4.5.42',
    date: '2026-05-05',
    kind: 'minor',
    summary: 'Audit close-out + onboarding prep for external admins',
    items: [
      'Winner Sans font installed at /public/fonts/WinnerSans-Bold.otf — the Headline pill now ships at the design intent on first render.',
      'Headline toggle is now a font picker — six chips (OFF / Winner Sans / Bebas Neue / Press Gothic / United Sans / Gotham / Barlow Cond). Each chip renders its own font so designers can preview before clicking. Active chip fills in the team color.',
      'Security audit I5: SSRF host allowlist on /api/players-sheet-sync. Master admin can only fetch CSV-export URLs from docs.google.com, sheets.googleapis.com, or *.googleusercontent.com — anywhere else returns a 400 with guidance.',
      'First-run welcome card on the dashboard for non-master staff (admin / content tier). Shows role + first action ("Open the Studio →") + pointer to Resources. Dismisses to localStorage so it never fires again per user.',
      'Resources page: new "What each role can do" reference card with concrete CAN / CAN\'T lists for master / admin / content / athlete tiers. Replaces the long-standing placeholder items in Getting started.',
      'Resources page (master only): new pre-flight checklist for onboarding a new admin — nine-step run-through covering invite, role gating, Drive sync, first test post, and what to do when something\'s off.',
      'Getting started section now shows real "Jump to the Studio / Files / Requests / role permissions" links instead of "coming soon" placeholders.',
    ],
  },
  {
    version: '4.5.41',
    date: '2026-05-05',
    kind: 'patch',
    summary: 'Stats tables show the prowiffleball.com wordmark logo',
    items: [
      'Replaced the "PWB" text pill above each stats table with the actual prowiffleball.com wordmark (public/brand/prowiffleball-logo.svg). Sits flush right at the top of the header row on Batting / Pitching / Rankings tables (Game Center, Team page, Dashboard). Hover bumps opacity slightly so it reads as a link, not decoration.',
    ],
  },
  {
    version: '4.5.40',
    date: '2026-05-05',
    kind: 'patch',
    summary: 'Hide-post error now names the missing migration',
    items: [
      'When clicking ✕ on a post fails because the db/011 migration hasn\'t been applied, the toast now says "Schema migration required — run db/011_generate_log_hidden.sql in the Supabase SQL editor" instead of the generic "server rejected the change." Server returns 412 Precondition Failed with the migration path embedded; client surfaces the detail directly.',
    ],
  },
  {
    version: '4.5.39',
    date: '2026-05-05',
    kind: 'patch',
    summary: 'Fix sidebar icons rendering as "!"',
    items: [
      'Replaced sidebar nav icons that lived in the Unicode Miscellaneous Symbols block (☰ ◫ ⚙ ▣ ⚑) with full-emoji codepoints (📥 📁 ⚙️ 📊 🏟). The old glyphs were missing from default macOS/iOS emoji fonts, so the browser fell back to its missing-glyph indicator and rendered them as "!" for everyone whose system didn\'t happen to have Symbola or Noto Sans Symbols installed. Affected: Requests, Files, Settings, ProWiffle Stats, Teams. Now renders correctly across every OS.',
    ],
  },
  {
    version: '4.5.38',
    date: '2026-05-05',
    kind: 'patch',
    summary: 'Security audit follow-up: RLS team-lock + AI rate limits',
    items: [
      'C1 fix: profile self-updates now lock team_id, email, and role_expires_at in addition to role. An athlete can only change their own display_name from the browser; team flips go through master/admin via /api/admin-people. db/012 migration tightens the WITH CHECK clause; safe to re-run.',
      'I2 fix: per-user-per-hour rate limits on /api/ideas, /api/captions, /api/auto-tag. Caps are role-specific — athletes 30/60/0 (auto-tag is staff-only), staff 300–1000 depending on endpoint. Returns 429 with Retry-After header when exceeded. Fails open if the rate-limit RPC errors so the AI surface degrades gracefully instead of breaking. Requires db/013 migration (atomic increment_rate_limit RPC + table).',
    ],
  },
  {
    version: '4.5.37',
    date: '2026-05-05',
    kind: 'minor',
    summary: 'Demo polish wave + pre-rollout security pass',
    items: [
      'Drive API key edit/clear is master-admin only — content/admin tier sees a read-only view (prevents an accidentally-deleted key from breaking Drive imports league-wide).',
      'Hype/Promo, Blank Slate, and Stat Card templates default ALL text fields to OFF — the imagery (or rendered card) is the content; adding text is opt-in. Deep-links that explicitly populate a field still un-hide it.',
      'High-resolution download: new "⤓ HD 2×" button next to Download. Renders an offscreen canvas at 2× resolution from primitives (genuinely sharper, ~2160×2700 for portrait), filename suffixed with _HD.',
      'Team Fade effect now constrained to the bottom HALF of the canvas — preserves athletes\' faces in the upper half while still giving text a colored runway along the lower third.',
      'Resources: master admin can hide built-in placeholder items (cloud-stored as resources-hidden), with a "↺ Restore N HIDDEN" affordance per section to undo.',
      'Stats tables: every batting/pitching/rankings table now carries a "For more in-depth stats and box scores, visit prowiffleball.com" link in the top-right.',
      'Hide-from-feed: master admin can ✕ a post on the dashboard recent-posts strip — server PATCHes hidden=true on generate_log so the post drops out of every team carousel and player page feed (db/011 migration adds the column; tolerant fallback lets the read still work pre-migration).',
      'Posts now display as Name_Template_MM/DD/YY across the dashboard, team carousel, player page, and Settings download history. Studio download filenames match.',
      'Player pages: master admin gets an "✎ Edit player info" button that opens an inline modal for nickname, jersey #, position, height/weight, birthdate, bats/throws, birthplace, and status. Saves through the existing upsertManualPlayer pipeline.',
      'Content calendar: master admin can click any cell to mark it with a post type — fills the cell in the type\'s color (matchup hype / highlight / score / stat leader / standings / idea). Marks persist per-team in cloud (key=content-calendar-{teamId}).',
      'New "Headline" toggle for Blank Slate, Highlight, and Stat Leader templates — wraps the largest visible text field in a team-colored rounded pill in Winner Sans with a soft drop shadow (TV-chyron energy). Drop /public/fonts/WinnerSans-Bold.otf to enable; falls back to Bebas Neue cleanly without it.',
      'Pre-100-user security pass: AI endpoints (/api/ideas, /api/captions, /api/auto-tag) now require a valid Supabase JWT (auto-tag is staff-only). /api/app-settings GET gates the Drive key to staff and per-team calendars to that team. /api/storage-presign caps signed-upload payloads at 25 MB and blocks athlete writes to overlay/effect buckets.',
    ],
  },
  {
    version: '4.5.36',
    date: '2026-05-04',
    kind: 'patch',
    summary: 'Stat Cards: drop subtitle, deepen drop shadow',
    items: [
      'Removed the "Across N BLW batters/pitchers" subtitle from percentile cards — the title alone reads cleaner and the population context isn\'t needed on the social card.',
      'Drop shadow deeper still: rgba(15,23,42,0.45) at 52px blur, 18px offset (was 0.32 / 36 / 14). Cards have real visual weight against busy photo backgrounds now.',
    ],
  },
  {
    version: '4.5.35',
    date: '2026-05-04',
    kind: 'patch',
    summary: 'Stat Cards: white frame stroke + deeper drop shadow',
    items: [
      'White frame around every stat card — 10px stroke centered on the card outline gives ~5px of visible white border. Polished print-frame look that doesn\'t inherit the team color.',
      'Drop shadow deepened across both card types: rgba(15,23,42,0.32) at 36px blur with 14px offset (was 0.13–0.15 alpha at 18–20 blur, 5–6 offset). Cards now lift off photo backgrounds with real visual weight.',
    ],
  },
  {
    version: '4.5.34',
    date: '2026-05-04',
    kind: 'patch',
    summary: 'Raw stat card: trim value font so multi-digit numbers don\'t collide',
    items: [
      'v4.5.33 set the raw card value font to 52% of body height. At that size, pitching cards with multi-digit values (25.0 / 11.68 / -1.85) ran into each other across columns and clipped the mini progress bar below. Reduced to 40%. Label + rank fonts trimmed slightly to keep proportions consistent.',
    ],
  },
  {
    version: '4.5.33',
    date: '2026-05-04',
    kind: 'patch',
    summary: 'Stat Cards: Space Grotesk + Inter, all 9 stats, bigger type, slight drop shadow',
    items: [
      'Typography aligned with the player page — Space Grotesk for headings + values, Inter for condensed labels and body text. Bypasses FONT_MAP and references the font stacks directly so the cards always read like the player page regardless of which Settings → Typography pick is active.',
      'Type sizes increased across the board. Raw card: header text ~+20%, value cell ~+25% (now 52% of body height vs 42%). Percentile card: title ~+15%, row labels/values bumped to ~36% of row height for stronger presence in social previews.',
      'Percentile cards now show ALL 9 stats per type — was 6. Hitting: AVG/OBP/SLG/OPS/BB%/K%/HR/PA/RBI/PA/R/PA. Pitching: ERA/WHIP/IP/K/K/4/BB/BB/4/FIP/K:BB. Same direction logic as the player page (asc on lower-is-better stats so the bubble points at "elite").',
      'Tightened percentile-row padding so 9 rows fit cleanly. Inner padTop reduced 7%→5%, header height 16%→13%, row spacing pulled in. Bar height up to 40% of row height (was 32%) and bubbles scale with bar — bigger, more legible.',
      'Slight drop shadow on every stat card. Raw card: rgba(15,23,42,0.15) blur 20 offset 6. Percentile card: rgba(15,23,42,0.13) blur 18 offset 5. Lifts the card off photo backgrounds without feeling heavy.',
      'Default box heights enlarged to accommodate the new content density: feed 540px (was 360) for percentile cards, portrait 580 (380), story 640 (420), landscape 540 (360).',
    ],
  },
  {
    version: '4.5.32',
    date: '2026-05-04',
    kind: 'patch',
    summary: 'Stat Card design pass: lower-third sized, exact reference layouts',
    items: [
      'Rewrote the stat-card renderer to match the master\'s reference designs exactly. Two distinct layouts:',
      'Raw Stats Card (Hitting / Pitching) — 4-column grid (~920×200 lower-third). Top header strip is a 135deg gradient in team color → team-dark with "2026 BATTING" / "2026 PITCHING" centered. Each column shows: stat label (uppercase 11-12px condensed muted), big value (heading face), rank line ("#32 / 64" condensed muted), and a 3px-thin mini progress bar. Last column is the headline stat (OPS+ for batting, FIP for pitching) rendered in TEAM ACCENT COLOR — value, mini-bar fill, all team-tinted.',
      'Mini-bar tier palette for raw cards: ≥50 blue (#3B82F6), ≥25 amber (#F59E0B), <25 red (#EF4444). Headline stat overrides with team color regardless of percentile.',
      'Percentile Card (Hitting / Pitching) — Savant-style bubble bars (~920×360-420 lower-third). Header reads "BLW BATTING/PITCHING PERCENTILE RANKINGS" + "Across N BLW batters/pitchers" subtitle. 6 rows of [70px label][bar with bubble][56px value]. Bubble has white ring + percentile number inside. Same 8-tier color palette as the player page (≥90 elite red C8302B → bottom-of-league navy 3F5A7A).',
      'Default box geometry sized for lower-third use across all four platforms — feed, portrait, story, landscape. Raw cards top out around 200px tall; percentile cards around 360-420px. All horizontally centered with healthy side margins.',
      'defaultCardBox now takes a cardType arg so raw vs percentile cards get different default heights.',
    ],
  },
  {
    version: '4.5.31',
    date: '2026-05-04',
    kind: 'minor',
    summary: 'Stat Card template — drop player stats into Studio compositions',
    items: [
      'New "Stat Card" template in Studio. Picks a player from the team and lays their actual stats onto the canvas with the same visual treatment as the player page card — rounded white card, team-colored accent bar, savant-style percentile bubbles or two-column raw stats.',
      'Four card types selectable from a 2×2 picker: Hitting · Stats (AVG / OPS+ / HR / OBP / SLG / OPS / RBI / PA), Hitting · Percentiles (savant bubbles for the same metrics + BB% / K% / HR/PA / RBI/PA), Pitching · Stats (ERA / FIP / IP / W-L / K/4 / WHIP / K / BB), Pitching · Percentiles (FIP / ERA / WHIP / K/4 / IP / W).',
      'Card draws programmatically via canvas primitives — no html2canvas, no DOM rasterization. Crisp at any export resolution. Same percentile color tiers as the player page (≥90 elite red, sliding through to bottom-of-league dark blue).',
      'Stats auto-fill from live data the moment a player is selected. Percentile lookups use percentileFor / derivedPercentileFor — same source the player page reads from, so what you see in Studio matches what you see on their page.',
      'Card sits between Overlay and Text in the layer stack — overlay chrome can frame it from above, captions can sit on top of it. Default box position varies by platform (lower half on feed/portrait/story, right side on landscape).',
      'Photo background, effects, overlays, and the optional caption text field all still work alongside the card. Same composer flow as every other template.',
      'New file: src/stat-card-renderer.js — pure canvas drawing functions for the four card types.',
    ],
  },
  {
    version: '4.5.30',
    date: '2026-05-04',
    kind: 'patch',
    summary: 'Cousin-pair athlete voice fix (Paul/Will Marshall, Logan/Luke Rose, etc.)',
    items: [
      'Generating content for Paul Marshall was pulling Will Marshall\'s athlete voice (and vice versa). Same root issue as the v4.5.20 Smith collision: athleteVoice map was keyed by TEAM|LASTNAME, so Paul (AZS|MARSHALL) and Will (AZS|MARSHALL) collapsed into one slot — whichever was last in iteration order won. Same trap hit Logan/Luke/Carson Rose on DAL and James/Justin Lee on LV.',
      'Map keys are now TEAM|FI|LASTNAME (e.g. AZS|P|MARSHALL vs AZS|W|MARSHALL). Lookup tries the cousin-safe composite key first, falls back to TEAM|LASTNAME for non-cousin lookups so legacy ideas without first-initial metadata still resolve.',
      'Fixed in three locations: src/pages/ContentStudio.jsx (dashboard idea generation), src/pages/PlayerPage.jsx (player-page idea modal), api/ideas.js (server-side voice attachment).',
      'Reinforced the AI seed-scope prompt so when the seed is "Paul Marshall," the model sees "Paul Marshall (P. Marshall)" with explicit anti-conflation language: "Do NOT confuse them with any other player who shares the lastname \'Marshall\' (cousin pairs exist on this team — match the FULL first name, not just the lastname)."',
    ],
  },
  {
    version: '4.5.29',
    date: '2026-05-03',
    kind: 'patch',
    summary: '"+ Add photo" button on Media gallery — drag-and-drop is now discoverable',
    items: [
      'PageDropZone now exposes an imperative `openPicker(files)` handle via forwardRef + useImperativeHandle so a parent component can trigger the same asset-type picker from any UI affordance.',
      'PlayerPage Media gallery card header now carries a red "+ ADD PHOTO" button. Click → native file picker → asset-type selector → uploads tagged with player context. Same flow as drag-and-drop, just discoverable.',
      'TeamPage Recent player media card gets the same treatment — team-tinted button so it reads on every team page.',
      'Empty-state copy updated to mention both paths: "Drag any photo onto this page to auto-tag it for {Player}, or tap the button below."',
      'Multi-select on the file picker so you can grab several photos at once — same asset-type applies to all (matches the existing drag-multi-drop behavior).',
      'Mobile bonus: tapping the button on iOS/Android opens the native photo picker, which on most devices includes a "Take photo" option — early start on the mobile camera feature.',
    ],
  },
  {
    version: '4.5.28',
    date: '2026-05-03',
    kind: 'patch',
    summary: 'Hotfix: PlayerPage white screen from v4.5.27 hooks-order bug',
    items: [
      'v4.5.27\'s handleDropUploaded useCallback was placed AFTER PlayerPage and TeamPage early returns ("Loading…", "Team not found", "Player not found"), violating React\'s Rules of Hooks (hook count has to be stable across renders). On the first render the hook didn\'t exist; on the second it appeared, and React white-screened the entire page.',
      'Moved both useCallbacks above every early return. Standard rules-of-hooks compliance.',
    ],
  },
  {
    version: '4.5.27',
    date: '2026-05-03',
    kind: 'minor',
    summary: 'Drag a photo onto a player or team page → auto-tag',
    items: [
      'New PageDropZone component wraps PlayerPage + TeamPage with window-level drag-and-drop. When you\'re already on a player\'s page (or a team page), you can now drag any photo from your downloads folder, finder, desktop, etc. straight onto the page.',
      'On dragenter the whole page dims with a brand-red border + a "Drop to add to {player name}" callout — impossible-to-miss target.',
      'On drop, a tight asset-type picker appears with 5 options for player drops (Headshot, Portrait, Hitting, Pitching, Other action) or 3 for team drops (Team photo, Venue, Logo). Pick one → file uploads with the canonical filename auto-built from URL context. Multi-file drops apply the same type to all.',
      'Filename construction uses the same buildPlayerFilename / buildTeamFilename helpers the existing tag system uses, so the new files are immediately discoverable by the avatar resolver, the gallery, and the Generate-page picker — no extra wiring.',
      'Compression pipeline runs first (1920px / q=0.85 default), so big drops don\'t bloat the cloud. Direct-upload path (v4.5.23) handles anything > 3MB.',
      'Toast on completion shows count + tagged subject. Local media state prepends so the photo appears in the gallery instantly without a refetch.',
    ],
  },
  {
    version: '4.5.26',
    date: '2026-05-03',
    kind: 'patch',
    summary: 'Idea pager renders top + bottom so you don\'t chase the mouse',
    items: [
      'Content Ideas pager (dashboard, team page, player page) now renders BOTH above and below the cards. The bottom one was the only paginator before, but card heights vary widely with text length — every page click moved the bottom pager and you had to chase the mouse to keep paginating. The top pager sits in a fixed position so you can click through pages without moving.',
      'Pager component takes a new `position="top"` prop that swaps border-top + top-margin for border-bottom + bottom-margin so the visual treatment matches the placement.',
    ],
  },
  {
    version: '4.5.25',
    date: '2026-05-03',
    kind: 'patch',
    summary: 'Photo picker filters to player + every modal centers properly',
    items: [
      'Profile photo picker now filters to media tagged for THIS player only — was showing every team-wide asset, which made finding the right shot a scroll-fest. Match is by lastName + firstInitial; cousin pairs (Logan/Luke Rose) get their own scoped lists. Falls back to all team media (with a clear note) when no player-tagged media exists yet.',
      'Header copy reflects the scope: "12 photos for Konnor Jaso" or "No tagged media for Konnor Jaso yet — showing all LAN media."',
      'All PlayerPage modals (PhotoPicker, ProfilePositionEditor, GeneratedIdeaModal) now render via createPortal to document.body — fixes the "modal opens off-screen, have to scroll to find it" bug. The fixed-position centering was being broken by some transform-having ancestor in the page tree; portaling to body sidesteps that entirely.',
      'Same fix applied to the overlay + effect upload modals in Studio so they always center on viewport regardless of how far down the page you scrolled before opening them.',
      'Body scroll lock while any modal is open — page underneath can\'t scroll out from under the modal.',
    ],
  },
  {
    version: '4.5.24',
    date: '2026-05-03',
    kind: 'patch',
    summary: 'BLW logo placed app-wide (sidebar, top bar, login)',
    items: [
      'Sidebar header — replaced the placeholder mark + typed "BLW Studio" text with the actual league logo file (/brand/blw-logo.svg). Logo at 48px, "BLW Studio" wordmark + "Big League Wiffle Ball" subline sit to its right.',
      'Top bar — added the logo next to the page title (28px on mobile, 36px desktop) so the brand reads on mobile where the sidebar is hidden by default.',
      'Login page — full logo replaces the placeholder mark on the main sign-in screen + Cloud-not-configured state. Sized at 96px to anchor the page.',
      'Drop-in updates — the league logo lives at /public/brand/blw-logo.svg. Swap that one file to refresh every surface app-wide; no code edits required.',
    ],
  },
  {
    version: '4.5.23',
    date: '2026-05-03',
    kind: 'minor',
    summary: 'Direct-to-Supabase uploads — bypass Vercel for big blobs',
    items: [
      'New endpoint /api/storage-presign mints a short-lived signed PUT URL so the browser can upload blobs DIRECTLY to Supabase Storage, skipping the Vercel function relay (and its hard 4.5 MB payload limit). Replaces the relay path for any blob > 3 MB.',
      'cloud.syncMedia / syncOverlay / syncEffect (and the awaitable mirrors used by the backup runner) now check blob size and route accordingly: small blobs through the existing /api/cloud-sync relay (one round-trip, simpler), big blobs through the direct path (two round-trips: presign + PUT, then a tiny metadata POST).',
      'Direct-upload failures fall back to the relay automatically so a transient presign error doesn\'t lose the upload — relay path then picks it up and the v4.5.22 fit-compression takes care of the size.',
      'Existing files in cloud are untouched. Only new uploads route via the new path. Read paths (signed download URLs from /api/cloud-sync) unchanged.',
      'Operator escape hatch: set localStorage["blw.upload.directMode"] = "0" to force every upload through the relay (debugging / rollback without redeploy).',
      'api/cloud-sync POST handler now accepts records that already carry a storage_path (no blob field) — that\'s how the metadata-only POST after a direct upload completes the round-trip.',
      'Photographer raw drops + future video clips now upload natively. Vercel function compute time per upload drops to near zero (no buffer-the-whole-blob-into-memory step).',
    ],
  },
  {
    version: '4.5.22',
    date: '2026-05-03',
    kind: 'patch',
    summary: 'Backup fixes: 413 payload limit + tolerant column writes',
    items: [
      'Vercel functions cap request payloads at 4.5 MB regardless of plan. Added compressToFitUploadLimit() that progressively re-compresses oversized blobs (1600px/q=0.82 → 1280/0.78 → 1080/0.72 → 800/0.65) until they fit. cloud.syncMedia / syncOverlay / syncEffect (and their awaitable mirrors used by the backup runner) now run blobs through it before base64 — fixes the "413 Request Entity Too Large" failures on high-megapixel sports cameras.',
      'Tolerant upsert in api/cloud-sync.js — when Postgrest rejects an upsert with "Could not find the X column", the server now strips that column and retries (up to 6 unknown columns per row). Mirrors the v4.5.8 fix for profiles.role_expires_at. Fixes the cascading 500s when overlays.mime_type or manual_players.profile_media_id columns are missing.',
      'Stopped the server from injecting mime_type / size_bytes into overlays + effects payloads — those tables don\'t have the columns and the read path doesn\'t use them. Saves a wasted round-trip per blob.',
      'Optional schema migration db/010 — adds mime_type + size_bytes to overlays and effects so blob metadata is consistent across all three tables. No-op if columns already exist.',
      'NOTE: db/005_player_profile_pic.sql adds manual_players.profile_media_id — if you haven\'t run it yet, the tolerant upsert will drop that column on each write (works fine, but profile-pic overrides won\'t persist). Run the migration to enable per-player profile pic picks.',
    ],
  },
  {
    version: '4.5.21',
    date: '2026-05-03',
    kind: 'patch',
    summary: 'Backup failures now show why',
    items: [
      'Cloud-sync POST helper now bubbles the server\'s actual error message to the caller. Previously a non-OK response logged the detail to the console but only returned `{ok:false, status}` — the failure summary on the Files page had no way to show what actually broke. Now it returns `{ok:false, status, error: "403: <message>"}` (parses JSON `{error,detail}` when present, falls back to raw text).',
      'Backup result banner adds a "FIRST ERROR PER FAILING KIND" block when totalFail > 0. Surfaces the first record name/id + the server error message for up to 4 failing kinds so root cause is one glance away instead of a devtools dive.',
    ],
  },
  {
    version: '4.5.20',
    date: '2026-05-01',
    kind: 'minor',
    summary: 'Demo polish wave: Smith fix, Studio re-layer, team strip, Resources upload',
    items: [
      'Cross-team avatar fix — Cam Smith on MIA was claiming Connor Smith\'s profile photo on SD because the avatar resolver had no team filter. Same-team match now wins; cross-team only kicks in when there\'s zero same-team media (handles traded players cleanly).',
      'AI tag jersey auto-fill — typing team + lastName + first initial now pulls the jersey number from the roster automatically when it uniquely identifies a player.',
      'Created posts now populate on Dashboard / Team / Player pages — fetchRecentGenerates was using plain fetch() which 401-d silently against the auth-walled cloud-sync endpoint. Switched to authedFetch.',
      'Roster source universalized — added a canonical-anchor dedup pass so "Eddie \'Nick\' Martinez" / "Andrew Ledet Ledet" / API ghost rows all collapse into one canonical entry per lastname.',
      'Studio layer reorder — the on-screen order now matches the conceptual stack: Picture + Photo Adjust → Effects → Overlay → Content. Effects render BELOW the overlay so brand chrome stays sharp.',
      'Replaced Team Duotone effect with a clean Team Fade — bottom-up gradient in the team\'s primary color.',
      'Team page leaders → full-width strip — the three big leader cards collapse into one card with one row each, percentile chips on the right.',
      'Hero gradients (player + team) — replaced the abrupt 240/260px wash with an edge-to-edge multi-stop fade.',
      'Team page social badges — always render IG / FB / TikTok chips; missing handles desaturate with "Not yet connected" tooltip. Master admin gets an inline "✎ EDIT" affordance.',
      'Stats tables — swapped the Team and Rank columns. Team reads first.',
      'Photo grids capped at 2 rows by default with "Show all" expand on player + team pages.',
      'Monthly content target is now editable per team (master admin only).',
      'Resources page — master admin can add custom links/files to any section inline. Welcome write-ups for athletes + admins anchor the top of the page.',
      'Search bar — replaced the tiny ⌘K hint chip with a visible "Search players, teams…" affordance.',
      'Content Ideas — added search + shuffle so the dashboard feels alive without burning AI tokens.',
      'Mobile dashboard — Queue / Data / Standings cards now fill width when wrapped.',
      'About footer copy refreshed in Settings.',
    ],
  },
  {
    version: '4.5.19',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Player of the Game template: hardcoded scoreboard layout',
    items: [
      'Locked the Player of the Game stat-box positions to the master\'s design pass: portrait reference is x=230/539/848, y=1165, fontSize 200, font United Sans Bold. Three boxes laid HORIZONTALLY (same Y, three X) so the eye reads a scoreboard rather than stacked text.',
      'Other platforms scale from the portrait reference: feed (1080×1080) → y=895, story (1080×1920) → y=1735, landscape (1200×675) → x=256/600/944, y=580, fontSize 160 to fit.',
      'Auto-fill on player select now populates ONE short value per box (HR / AVG / OPS+ for batters, IP / K4 / W for pitchers) instead of a full multi-stat string. Matches the scoreboard layout where each box should hold a single number, not a sentence.',
    ],
  },
  {
    version: '4.5.18',
    date: '2026-04-30',
    kind: 'minor',
    summary: 'Player of the Game template + uploaded-overlay tile redesign',
    items: [
      'Player of the Game template now player-centric — picking a player from the team auto-fills three Stat Box fields. Replaces the old Title / Subtitle pair.',
      'Stat Box copy renders BLACK with a soft drop-shadow (rgba(0,0,0,0.45) blur 6 offset 0/2) so the boxes pop legibly on light or dark backgrounds. Field config carries the shadow declaratively, no special-case render code.',
      'Auto-fill on player select: Box 1 = name + #jersey, Box 2 = stat line (OPS+ / FIP / etc.), Box 3 = team name uppercase. Each box is freely editable.',
      'Uploaded-overlay tiles in the Studio overlay picker no longer render as ugly dark text-only tiles. Match the preset tile aesthetic: image-as-background thumbnail, top-right team chip, bottom-gradient caption with the formatted name (extension stripped, underscores → spaces).',
      'Object URLs allocated for uploaded-overlay thumbnails are revoked on cleanup (team change, template change, unmount) so we don\'t leak blob URL handles.',
    ],
  },
  {
    version: '4.5.17',
    date: '2026-04-30',
    kind: 'minor',
    summary: 'Athlete voice in captions + Blank Slate template + Download via Studio',
    items: [
      'Athlete voice now feeds /api/captions, not just /api/ideas. When the spotlit player has a self-authored About-me block (vibe, references, walk-up music, fun facts, content notes), the caption drafter grounds tone and vocabulary in their own words. Both initial drafts AND per-platform regenerates pass it through.',
      'New Studio template: Blank Slate. Pure background photo with an optional headline overlay — no badges, no chrome. Designed for the fastest path from raw asset to social-ready export.',
      'Files page preview lightbox: new "✦ Download via Studio" action on the tagged-file viewer. One click drops you into Studio with the Blank Slate template active and the photo pre-loaded as the background. No more "find the file → re-upload → tag → export" loop when you just want a quick crop or a headline overlay.',
      'Generate.jsx now reads ?bgMediaId=<id> from the URL and looks up the media record from IndexedDB on mount, populating the canvas before any user input. Pairs with the Files preview deep-link.',
    ],
  },
  {
    version: '4.5.16',
    date: '2026-04-30',
    kind: 'minor',
    summary: 'High-value polish: Studio rename, Resources page, social handles, Settings cleanup, athlete DM',
    items: [
      '"Generate" renamed to "Studio" everywhere — sidebar nav, page header, browser tab. Path stays /generate so existing bookmarks resolve. Sidebar sparkle icon now rotates with a soft accent-tinted glow on hover and the active state.',
      'New Resources page (/resources) with a clean shell ready for SOPs / training videos / FAQ / brand guidelines / team assets. Each section has anchor jumps, "coming soon" placeholders for items waiting on copy, and an admin-only Operations section. Athletes see everything but Operations.',
      'Team page: owner replaced with social handle chips (Instagram / X / TikTok). Each chip is a clickable link — empty handles are hidden. Populate via TEAMS[i].socials in src/data.js.',
      'Player page: "Start of roster" / "End of roster" placeholder pills removed from the prev/next teammate nav. The position chip ("2 / 9") still anchors center.',
      'Settings: removed "Team colors" card (was purely informational, replaced by per-team brand guidelines under Resources). Removed "Other integrations" card (redundant with primary integration cards). Roster diagnostic now collapses by default — click to expand. Typography simplified to a 4-button row (BLW Classic, BLW MVP, Punch, Data Pro) — no more elaborate JOSH JUNG previews.',
      'New Settings card for athletes: "Message the admin" — single textarea + Send button. Routes via the existing Requests pipeline as type=\'message\' so it lands in the master admin\'s inbox without polluting the priority / template / type fields.',
    ],
  },
  {
    version: '4.5.15',
    date: '2026-04-30',
    kind: 'minor',
    summary: 'Round 2: mobile template selector, dark mode contrast, profile-data empty state',
    items: [
      'Generate page on mobile: Template Type card now sits at the TOP of the controls column, not buried at the bottom of the right-side preview column. Picking a template is the first decision the user makes, so it should be the first card they see — used to require scrolling past Team / Player / Media / Overlay / Effects / Download to reach it.',
      'Dark mode contrast pass: bumped lightness on textSecondary (0.74 → 0.88), textMuted (0.55 → 0.74), textOnDarkMuted alpha (0.55 → 0.78), border (0.32 → 0.40), borderLight (0.26 → 0.32), divider (0.22 → 0.28). Also added bright successText / warningText / infoText / dangerText variants for dark mode — they were falling back to dark hex and were invisible on dark status backgrounds.',
      'Player page: when no CSV-driven vitals exist, the page used to render five rows of em-dashes (HT/WT —, Birthdate —, etc.). Now shows a single "NO PROFILE DATA YET" empty state explaining that the master can populate via Settings → Player bio import. Removes the "is the data broken or is there just no data?" ambiguity.',
    ],
  },
  {
    version: '4.5.14',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Fix canonical names: Drew Baalman, Michael Stiles (player-confirmed)',
    items: [
      'Per the master\'s player-self-reported roster: CHI\'s "Drew Balmaan" → "Drew Baalman", MIA\'s "Mike Stiles" → "Michael Stiles". Canonical roster names now match how the players themselves spell them.',
      'Reverse aliases added: any legacy media or stat row tagged with the old spelling still resolves to the same record. No data lost.',
      'admin-player-trades.js preset list updated to match (was hardcoded to "Mike Stiles" and "Kyle Vonschleusingen").',
    ],
  },
  {
    version: '4.5.13',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Jersey numbers populated across the canonical roster',
    items: [
      'Added explicit jersey numbers to ~60 canonical roster entries across all 10 teams. AZS / BOS / CHI / DAL / LAN / LV / MIA / NYG / PHI / SDO each now carry the master\'s known jerseys. Players without a confirmed number stay un-numbered until the league-wide directory fills in.',
      'Effect: auto-tag roster chips on the Files page now read "AZS #34 · A.LEDET · ROSTER" instead of "AZS · A.LEDET · ROSTER". One-click tagging populates the right jersey instead of leaving num blank.',
      'Cosmetic fix: Kyle VonSchleusingen capitalization corrected. Two pending diffs to confirm with master before changing canonical names: Drew Balmaan vs Baalman, Mike Stiles vs Michael Stiles.',
    ],
  },
  {
    version: '4.5.12',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Roster chips: drop "#??" placeholder when jersey is unknown',
    items: [
      'Auto-tag "Pick a player" roster chips on the Files page used to read "MIA #?? · J.Adams" when no jersey was on file. The "??" was distracting and made every chip look like it had broken data even when team + name were already useful. Now reads "MIA · J.Adams" — the # part appears only when there\'s a real number.',
      'Jersey numbers populate automatically from the canonical roster, manual_players records, or the live API stat rows (whichever has them first). To bulk-add jerseys for a team, paste the list in chat and they go into CANONICAL_ROSTER_2026 in src/data.js.',
    ],
  },
  {
    version: '4.5.11',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Drive cloud-sync: auto-push for masters with pre-existing local config',
    items: [
      'v4.5.10 introduced cloud-sync but the Update button was greyed out when the saved key matched the draft, so masters with a previously-saved key couldn\'t trigger the initial cloud push without first changing the value.',
      'New: Settings auto-pushes once when the master loads the page, the cloud config is empty, and they have a key in localStorage. Idempotent — never overwrites a non-empty cloud config from another master session.',
      'Also added a manual "Sync now" button next to Save / Remove so master admins can force a re-push at any time without editing the key.',
    ],
  },
  {
    version: '4.5.10',
    date: '2026-04-30',
    kind: 'minor',
    summary: 'Cloud-synced Drive config — every admin inherits master\'s setup',
    items: [
      'Drive API key + folder list now cloud-sync via a new app_settings table. Master admin pastes once in Settings → all other admins (including time-boxed ones like adamskay131@gmail.com) auto-pull on sign-in. No more passing the API key through DMs to every new user.',
      'New /api/app-settings endpoint (GET = any authed user, POST = master_admin only). Backed by a single key/value JSONB row so future shared config (brand kits, league templates, feature flags) can land here without schema changes.',
      'Settings → Google Drive card now shows a status pip: "☁ CLOUD-SHARED · MASTER WRITES" for master, "↻ SYNCING TO CLOUD" while the push is in flight, "✓ SYNCED · ALL ADMINS" on success. Non-master users see explanatory copy that the config is inherited.',
      'Folder add/remove/rename in Files page also push to cloud automatically. Saving propagates to every other admin within ~one auth-state-change cycle (next sign-in or page reload).',
    ],
  },
  {
    version: '4.5.9',
    date: '2026-04-30',
    kind: 'minor',
    summary: 'Bulk overlay upload — multi-select or drag-drop, one set of metadata',
    items: [
      'The overlay upload modal now accepts MANY PNGs at once. Multi-select on the file picker, or drag a folder onto the dropzone — every file picked becomes its own overlay record, all sharing the template type / platform / team you set in the modal.',
      'Each bulk-uploaded overlay is named after its filename (so "DAL_Game1.png" → "DAL_Game1"). Single-file upload still has the editable name field — no behavior change for one-at-a-time flows.',
      'Live progress bar shows "UPLOADING 3 / 12" as each file syncs to the cloud. The first uploaded overlay auto-selects when done so you see an immediate result instead of digging through the picker.',
    ],
  },
  {
    version: '4.5.8',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Hotfix: 403 on protected endpoints when role_expires_at column missing',
    items: [
      'v4.5.7 added a SELECT for profiles.role_expires_at on every authed request. If the column hadn\'t been added via the migration SQL yet, the SELECT errored, profile resolved to null, and every requireRole / requireAdmin call 403\'d — including usage meter, ideas generator, and other admin surfaces.',
      'Server now mirrors the client\'s graceful two-step fallback: if the SELECT errors with "role_expires_at", retry without the column. Expiry enforcement just no-ops until the migration is run.',
      'Apologies for the brief outage — the column-missing path is now tested.',
    ],
  },
  {
    version: '4.5.7',
    date: '2026-04-30',
    kind: 'minor',
    summary: 'Time-boxed elevated access (auto-revoking master grants)',
    items: [
      'New profiles.role_expires_at column. When set, the elevated role auto-revokes the moment the timestamp passes — no cleanup script needed. Server-side enforcement: requireUser() in api/_supabase.js demotes the role to null when expired, so every protected endpoint rejects the request even on a still-valid JWT. Client mirror in auth.jsx so the UI also reflects the demotion.',
      'New <TempAccessBanner /> at the top of the app — renders only for users with an active expiry. Shows "MASTER ACCESS · expires in 5h 23m" with a live countdown. Color drifts from amber (>1h) to red (<1h) as the timer winds down. When zero hits, the user sees "MASTER ACCESS EXPIRED" and the profile auto-refreshes so the demotion takes effect immediately.',
      'Use case: granting a temporary master grant to a tester, a contractor, or a second account without having to remember to revoke it manually.',
    ],
  },
  {
    version: '4.5.6',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Roster dedup by lastName + jersey (handles malformed CSV-imported rows)',
    items: [
      'The team dashboard / roster surface was showing duplicate teammates whose firstNames differed but who were the same person — e.g. "Andrew Ledet" #34 (canonical) AND "Andrew Ledet Ledet" #34 (CSV row with first_name set to the full name), or "Nick Martinez" (no num) AND "Eddie \"Nick\" Martinez" #10 (richer CSV data).',
      'Strengthened the v4.5.5 roster dedup with a jersey-first merge pass. Two entries that share lastName + jersey are treated as the same player. The cleaner-named one (lower duplicate-lastName score, fewer embedded quotes, shorter firstName) is kept; the other folds its hasStats / hasMedia / num signals in.',
      'Companion cleanup SQL is in this release\'s notes — find any manual_players row whose first_name contains its last_name twice (the "Andrew Ledet Ledet" shape) and either fix or delete it.',
    ],
  },
  {
    version: '4.5.5',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Roster pills: drop the ghost-Ledet duplicate + harder fallback labels',
    items: [
      'Root cause of the persistent "Next: LEDET" pill on Andrew Ledet\'s page: the live API was returning a bare "Ledet" stat row with no firstName alongside the canonical "Andrew Ledet" row. getTeamRoster keyed them separately (fullNameKey \'\' vs \'andrew\') and emitted two roster entries — a real one and a ghost. The ghost showed up as the "next teammate" because both lastNames were identical.',
      'Fix: dedup pass at the end of getTeamRoster. When two entries share a lastName and one has no firstName, the no-firstName ghost folds its signals (hasStats / hasMedia / num) into the named entry and is dropped. Safe merge — only fires when the named entry is unambiguous OR the ghost\'s jersey number matches a specific named entry.',
      'Also hardened the pill label resolver: when no firstInitial / firstName is available, falls back to "#34 LEDET" using jersey before giving up to lastName-only.',
    ],
  },
  {
    version: '4.5.4',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Jersey safety net + roster-pill labels show first initial',
    items: [
      'CSV bio-import: jersey number is now a secondary disambiguator. Resolver hierarchy is exact firstName → exact jersey → legacy quirk fallback → first-initial multi-row fallback. Catches CSV variants like "Luke A." vs "Luke" that would otherwise miss the exact-name path on a same-team cousin pair.',
      'Roster pills (top-right teammate prev/next on player pages) now read "A. LEDET" instead of just "LEDET". On rosters with multiple Ledets / Roses / Marshalls / Lees, the next pill used to look like a self-reference because both pills displayed only the lastName. First initial is included whenever available; legacy entries without a firstName still fall back to lastName-only.',
    ],
  },
  {
    version: '4.5.3',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Server-side: fix the same collision in CSV bio-import path',
    items: [
      'api/players-sheet-sync.js had the same "if exactly 1 manual_players row matches the lastName, use it" fallback as the client-side getPlayerByTeamLastName. With Carson being the only DAL Rose row, a CSV row for Logan or Luke would overwrite Carson\'s bio. Same trap was lying in wait for any future CSV import where one cousin had a record and others didn\'t.',
      'Tightened: server now only falls back when the existing single row has NO first_name at all (legacy quirk case). Multi-row + no firstName match → INSERT a new row, never overwrite an unrelated cousin.',
      'No code path remains that can silently merge one Rose/Lee/Marshall into another. Three-Rose collision is now closed end-to-end (write path v4.5.1, read path v4.5.2, CSV import v4.5.3).',
    ],
  },
  {
    version: '4.5.2',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Read-path: stop serving Carson Rose\'s About-me to Logan and Luke',
    items: [
      'getPlayerByTeamLastName had a "if exactly 1 manual_players row matches the lastName, use it" fallback that was meant to handle legacy rows with blank firstName. With Carson Rose being the only DAL Rose with a manual_players row, the fallback served his About-me block under Logan AND Luke\'s URLs. That\'s the root cause of the "all Roses share the same About section" bug.',
      'Tightened: the fallback now only fires when the single candidate has NO firstName at all (the actual legacy-quirk case). A row with an explicit firstName that doesn\'t match the URL is treated as a different player — no cross-contamination.',
      'Pair this with the v4.5.1 write-path fix and the Rose pages now resolve cleanly: Carson sees Carson, Logan sees an empty card (no manual record yet), Luke sees an empty card (his data is sitting under the "Luke Ross" typo row).',
    ],
  },
  {
    version: '4.5.1',
    date: '2026-04-30',
    kind: 'patch',
    summary: 'Fixed manual_players collision (Roses sharing About-me records)',
    items: [
      'Tightened upsertManualPlayer matching rules. The OLD logic matched on (team, lastName, firstInitial) which collapsed every Rose with initial "L" into a single record — editing Logan\'s About-me overwrote Luke\'s. Same trap caught Marshalls and any future twin pair sharing an initial.',
      'New matching priority: (1) firstName + lastName + team [exact identity, used by every UI form], (2) jersey + lastName + team, (3) firstInitial + lastName + team but ONLY if unique on team, (4) lastName + team but ONLY if unique. Ambiguous matches now create a new record instead of overwriting an existing one — losing data is worse than a duplicate an admin can clean up.',
      'Existing collided records still need a one-time cleanup in Supabase — the code fix prevents future collisions but can\'t un-merge data that\'s already been overwritten. See post-deploy notes for cleanup SQL.',
    ],
  },
  {
    version: '4.5.0',
    date: '2026-04-30',
    kind: 'minor',
    summary: 'Demo prep · Round 1: mobile overlay sync, name-collision fixes, brand chrome',
    items: [
      'Mobile overlay sync — overlays uploaded by one admin now show up on every other admin\'s device within 60 seconds, not 10 minutes. Three fixes compounded: lowered the global hydrate throttle from 10 min → 60 sec, retriggered hydrate when the auth session lands (closing a JWT race that silently 401\'d on first mobile mount), and force-refreshed overlays on every Generate-page mount instead of only on team-select.',
      'Name collision fixes — Logan/Luke Rose, James/Justin Lee, and the Marshall pair on AZS no longer cross-wire each other\'s media or trap users on prev/next teammate nav. Disambiguation now uses lastName + firstInitial + jersey in combination, with legacy untagged records still surfacing rather than being silently dropped.',
      'Top-bar brand chrome — the page H1 no longer duplicates in the workspace header. The chrome reads "BLW Studio" everywhere, with the actual page title still driving the browser tab via document.title.',
      'BLW + ProWiffleball logos — branded marks land in the sidebar header, login screen, and footer credit. Drop replacement SVGs at /public/brand/blw-logo.svg, blw-mark.svg, or prowiffleball-logo.svg to swap them across the app without touching code.',
      'Renamed app from "BLW Content Hub" to "BLW Studio" everywhere it appeared (window title, sidebar, login, settings about, file manifest, changelog modal).',
    ],
  },
  {
    version: '4.4.2',
    date: '2026-04-29',
    kind: 'patch',
    summary: 'Renamed templates: Batting Leaders → Stat Leader, Pitching Leaders → Player of the Game',
    items: [
      'Batting Leaders → Stat Leader (🏏). Repositioned for any single-stat spotlight, not just OPS+.',
      'Pitching Leaders → Player of the Game (🏆). Repositioned as a standout-game spotlight.',
      'Internal template ids stay stable (`batting-leaders`, `pitching-leaders`) so existing requests, generate-log entries, content ideas, and bookmarks keep resolving.',
    ],
  },
  {
    version: '4.4.1',
    date: '2026-04-29',
    kind: 'patch',
    summary: 'Athletes can only edit THEIR OWN player About-me',
    items: [
      'New strict 1:1 link between a player record and an athlete profile via manual_players.user_id. Athletes can edit the About-me block ONLY when this matches their auth user.id — no more "any teammate can edit any teammate" leakage.',
      'Master admin gets a "Link athlete account" picker inside the AthleteVoiceCard: pick which athlete profile owns this player. Picker fetches /api/admin-people, filters to athlete-role accounts, groups by team. ✓ LINKED chip surfaces when the binding is set.',
      'Athletes whose account isn\'t linked to a player yet still see other players\' About-me cards (read-only) but can\'t edit anything. Master admin links them via the picker on their player page.',
    ],
  },
  {
    version: '4.4.0',
    date: '2026-04-29',
    kind: 'major',
    summary: 'Requests overhaul + athlete role + athlete voice for AI ideas',
    items: [
      'Requests have TYPES now: Content, Profile update, Bug, Template, Feature, Integration. Each type opens a tailored form so a bug request asks for repro steps, a profile-update asks what to change, a content request asks for player + template + athlete input.',
      'New RequestModal — single progressive form with type picker, polished chrome, priority chips (added CRITICAL), needed-by date, and a confirmation that shows where notifications will land. Replaces the inline three-field form.',
      'Athlete role gets first-class treatment: athletes see ONLY their own requests (server-enforced via requester_user_id, with email fallback for legacy rows). Their team auto-pins on the form, status-flip buttons hide, and the page header switches to a personal "your requests" voice.',
      '"Notify requester" button on completed requests opens a pre-filled mailto: with subject + body, then stamps notified_at so a follow-up click reads "Re-notify". Real Resend/SendGrid pipeline lands later — the mailto path covers v1.',
      'Type filter chips above the existing status chips so you can scope by "show me all bugs" or "show me high-priority profile updates."',
      'New per-card layout: type badge tinted by category, priority dot (with explicit CRITICAL chip when relevant), team chip, player chip, needBy countdown ("Due in 3d", "Overdue 2d"), then the title + status — reads at a glance without opening Brief details.',
      'Athletes get an editable "About me" card on their player page (master_admin can edit anyone\'s). Free-form fields: vibe, references, walk-up music, fun facts, content notes. Stored as JSON on manual_players.athlete_voice.',
      '/api/ideas reads the athlete voice for any sampled player and weaves it into its prompt as an "ATHLETE VOICE" block. Stronger signal than stats alone — captions get the player\'s actual identity, not just generic stat lines.',
    ],
  },
  {
    version: '4.3.0',
    date: '2026-04-29',
    kind: 'minor',
    summary: 'Asset-type rename + per-team storage breakdown + roster-fallback AI chips',
    items: [
      'Asset types renamed: ACTION → HITTING, ACTION2 → PITCHING, HIGHLIGHT2 → HYPE. Added GROUP for multi-player shots. Old strings still resolve everywhere they\'re read (avatar resolver, photo picker, idea suggester) so existing media tagged with the legacy names continues to work — a one-time SQL migration is optional.',
      'Cloud storage "Breakdown by team" now reads team from the media table\'s `team` column instead of trying to parse it from object filenames (storage paths are `{uuid}.png`, no team prefix). Every team that has uploaded media now appears with its own bar + color.',
      'Drag-and-drop and Bulk import card alignment fixed: label was collapsing to inline baseline, leaving the dropzone shorter than the neighboring card. Both children now flex-stretch and use border-box so the 2px borders sit inside the grid cell.',
      'AI candidate chips now include a roster fallback: whenever the team is identified (by AI or user pick), the FULL roster of that team surfaces as one-click chips so you can pick the right player even when the AI returned no specific candidate. ROSTER badge distinguishes these from AI-ranked suggestions.',
      'tag-heuristics.js learns the new vocabulary: "batting" / "swing" → HITTING, "pitching" / "mound" → PITCHING, "hype" / "intro" / "walkup" → HYPE, "group" / "squad" → GROUP.',
      'auto-tag system prompt updated with the new asset-type list + a note keeping the legacy strings recognizable so the model returns the new names even on photos labeled with old conventions.',
    ],
  },
  {
    version: '4.2.1',
    date: '2026-04-29',
    kind: 'patch',
    summary: 'Status badge + priority dot palette pulls from theme tokens',
    items: [
      'StatusBadge (Pending / In Progress / Approved / Revision / Completed) and PriorityDot (high / medium / low) no longer hardcode hex colors — they read from theme tokens just like every other surface.',
      'Added successText / warningText / infoText / dangerText tokens to theme.js so dark-mode flips and any future palette tweaks reach every status surface automatically.',
    ],
  },
  {
    version: '4.2.0',
    date: '2026-04-29',
    kind: 'minor',
    summary: 'Per-team monthly carousel + posted/draft toggle',
    items: [
      'New "Posts this month" carousel under the progress bar on every team page. Horizontal scroller of every generation for that team this month with thumbnails, template, and date.',
      'Master admin can toggle each post between Posted (✓) and Draft (✕). Drafts grey out + decrement the counter on the progress bar; flip back and they brighten + increment. Optimistic local update with a background PATCH so toggles feel instant.',
      'Dashboard "Recent posts" strip now ALWAYS renders (with empty state) so the surface is visible from a cold install. Unposted entries are greyscale + carry a "DRAFT" tag, mirroring the team carousel for visual consistency.',
      'New PATCH endpoint on /api/cloud-sync for partial record updates. Field allow-list per kind keeps the surface tight; `generate-log.posted` is the first patchable field.',
      'Counter on the progress bar derives from posted=true entries only. The 12-post target is the publishing goal — drafted-but-not-posted work no longer inflates the number.',
      'SCHEMA: requires a one-time `ALTER TABLE generate_log ADD COLUMN posted BOOLEAN NOT NULL DEFAULT TRUE;` in Supabase. Without it, every post stays in the "posted" state by default and the toggle no-ops.',
    ],
  },
  {
    version: '4.1.1',
    date: '2026-04-29',
    kind: 'patch',
    summary: 'AI tagging now returns first initial + jersey number',
    items: [
      'Auto-tag API was missing firstInitial in both its prompt and its response shape — vision results never carried it through. Schema now requires firstInitial alongside lastName/num; roster context sent to the model includes "K.JASO #03 (Konnor)" so the model can pick the right initial for cousin pairs.',
      'Server-side roster lookup fills in firstInitial AND num when the model returns a confident lastName but forgets the disambiguator (or the photo cropped the jersey). Single-record lastname matches auto-resolve.',
      'Jersey-number OCR prompt strengthened: explicit instruction to attempt every jersey location (chest, back, sleeves, hat, helmet), pad to 2 digits, and surface partial reads as candidates.',
      'Files candidate chips now show the first initial (e.g. "DAL #07 · L.ROSE 84%") so cousin pairs are distinguishable at a glance, and one-click apply fills in the initial too.',
    ],
  },
  {
    version: '4.1.0',
    date: '2026-04-29',
    kind: 'minor',
    summary: 'Files preview fix, cloud overlays, brief drawer, monthly progress, smarter AI tagging',
    items: [
      'Files preview lightbox rewritten: portal-mounted to escape ancestor stacking contexts, body scroll-locked while open, blob URL lifecycle owned by a proper hook — no more dark-screen / scroll-to-find-it bugs.',
      'Overlays now sync universally across users — Generate auto-pulls fresh overlays on team-select and a manual "↻ Sync" button surfaces uploads from other machines without waiting for the 10-min global hydrate.',
      'Brief context drawer on Generate: when you arrive from a content idea (dashboard, team page, player modal, or a Request) a small panel below Effects shows the original headline, narrative, stat pills, and platform-tabbed captions. Read-only with one-click copy.',
      'Monthly content progress on every team page: counts every published post for the team since the 1st of the calendar month, with a 12-post target. Glows team-tinted gold + 🔥 badge once you cross target.',
      'Smarter AI photo tagging: vision API now returns up to 5 ranked roster candidates when only partial info is visible (e.g. clear jersey number, ambiguous team). Files page shows the candidates as one-click chips so you pick the right player instead of typing.',
      'Server-side generate-log endpoint accepts team + since + fields filters so the progress bar runs as a count query, not a full record fetch.',
      'Role model consolidated: Admin tier is dormant. Master Admin handles trades / CSV bio import / people management / roster diagnostic; Content team gets everything else (incl. player photo edits).',
      'Hand-curated release log surfaced as a clickable popup from the sidebar footer + Settings About card.',
    ],
  },
  {
    version: '4.0.0',
    date: '2026-04-29',
    kind: 'major',
    summary: 'Requests detail overhaul + 9 polish/bug fixes',
    items: [
      'Requests page: every card has a "Brief details" disclosure with narrative, stats cited, suggested template, photos to reach for, and a flat prefill listing — plus a permanent red "Open in Generate" CTA that auto-populates team, template, and every line of copy.',
      'Idea payload now travels with the request, fenced inside the existing note column (no schema migration), so deep-links from Requests → Generate carry the FULL idea context.',
      'Roles consolidated: Admin tier is dormant; Master Admin handles trades, CSV bio import, people management, raw API tools. Content team gets everything else (incl. player photo edits). View-as picker offers Content + Athlete.',
      'Caleb Jeter avatar fix: lastname-unique fallback in resolver so a stale FI mismatch no longer blanks single-name players.',
      'Profile-pic editor: unified translate+scale transform — pan and zoom apply uniformly on both axes regardless of source-image aspect.',
      'Pitching card values auto-shrink (34→30→26→22 by char length) with nowrap+ellipsis so ERA/WHIP/K/4 never overflow.',
      'FIP moved to the end of both pitching tables.',
      'Red dot removed from the IG handle chip.',
      'Version footer auto-rolls every Vercel deploy — semver + short SHA + clickable changelog popup.',
      'Team page forces scroll-to-top on every team change.',
    ],
  },
  {
    version: '3.3.0',
    date: '2026-04-29',
    kind: 'minor',
    summary: 'Generate-content modal on player pages',
    items: [
      'Player profile CTAs: "Generate Stat Post" became "Generate content"; clicking pops up a single AI-drafted idea for that player with re-roll, then hands off to Generate.',
      'Removed the Highlight button from player profiles — the modal flow replaces it.',
      'Fixed Generate drag-to-pan getting stuck mid-drag (pointer listener identity churning).',
      'Recent posts strip moved to the bottom of the dashboard, below the Top-10 leaderboards.',
      'Two more player-page white-screen fixes (Rules of Hooks: new useCallbacks must live above early returns).',
    ],
  },
  {
    version: '3.2.0',
    date: '2026-04-29',
    kind: 'minor',
    summary: 'Team/Player News template + custom fonts',
    items: [
      'New 3-line "Team/Player News" overlay template with multi-layer drop shadows and Press Gothic display type. Layout is locked at 120pt × (540, 1010/1138/1266) for every platform.',
      'Three new local fonts available in Generate: Gotham Bold, Press Gothic, United Sans Bold. FontFace API explicit preload so canvas never falls back to Times.',
      'Two-way player hero stacks pitching card UNDER batting card with full ERA/IP/K/4/WHIP percentiles.',
    ],
  },
  {
    version: '3.1.0',
    date: '2026-04-28',
    kind: 'minor',
    summary: 'Player page polish + Savant percentile bubbles',
    items: [
      'Stat tile grids on player pages replaced with Savant-style animated percentile bubbles (9 batting, 9 pitching) under "BLW Batting/Pitching Percentile Rankings" headlines.',
      'Sticky compact mini-hero on scroll, prev/next teammate keyboard navigation, recent posts featuring the player surfaced in their gallery.',
      'IG handle chip moved below the avatar (clears the tier badge); Hype button removed.',
      'Cousin pair fix: Logan + Luke Rose now both render with their own bio info.',
      'New 1st/2nd/3rd overall rank badges (amethyst, emerald, ruby).',
      'Replaced rank-1/2/3 glow palette with the gemstone tones.',
    ],
  },
  {
    version: '3.0.0',
    date: '2026-04-28',
    kind: 'major',
    summary: 'Dashboard content drafting + AI ideas',
    items: [
      'Dashboard "Generate Content" section rebuilt as editorial idea cards with narrative, stat pills, expandable caption tabs (Instagram/X/Story), and a context-aware "More about {Player/Team}" regen.',
      'Cap of 4 visible ideas per page with prev/next pagination.',
      'AI prompt overhaul: stratified player sampling, 8-angle diversity menu, anti-paraphrase rules, league-context as research-not-assignments.',
      'League Context: master-admin-editable narrative blob (trades, draft, storylines) feeds every AI generation.',
      'Content ideas persisted server-side with a 14-day rolling window and surfaced on team + player pages.',
      'View-as: master admin can preview the app as any athlete on any team.',
      'Team scope dropdown on the dashboard locks generation to one team.',
      'Recent posts strip surfaces the last 10 downloads across the team.',
      'Files preview dark-mode bug fixed (modal background was resolving to navy against the backdrop).',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-04-28',
    kind: 'minor',
    summary: 'MVP polish + version tracker',
    items: [
      'Skeleton loaders on every page-level fetch, route transition fades, empty states.',
      'Tabular-nums everywhere stat numbers render so columns line up.',
      'Live version tracker in the footer + Settings.',
      'Default font hierarchy locked across surfaces.',
    ],
  },
  {
    version: '2.0.0',
    date: '2026-04-28',
    kind: 'major',
    summary: 'Design system overhaul',
    items: [
      'Five-pass design refactor: kill side-stripes + em-dashes, team-color drift via scoped CSS variables, full hover/focus/active states, OKLCH brand-tinted neutrals, progressive disclosure on Generate.',
      'Unified theme tokens — every surface now reads from the same palette + radius + spacing system.',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-04-27',
    kind: 'minor',
    summary: 'Profile-pic positioning + cousin disambig',
    items: [
      'Profile-pic pan/zoom positioning persisted to manual_players + applied to every avatar surface (player hero, team roster card, content calendar).',
      'Photo pan/zoom + exposure controls on Generate Custom mode.',
      'Single source of truth for player avatars (resolvePlayerAvatar).',
      'Cousin avatar disambiguation by jersey number + protect legacy fallback (Marshall, Lee, Rose).',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-04-24',
    kind: 'minor',
    summary: 'Bulk media import + 3-scope library',
    items: [
      'Bulk import from Google Drive folders with row-level edit + "stamp to all" shortcut.',
      'Bulk apply bar with always-editable fields and "Select all" inline.',
      'League-wide media bucket — third scope alongside player + team.',
      'Team-branded content calendar.',
      'Incremental cloud backup that skips already-uploaded media.',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-04-17',
    kind: 'major',
    summary: 'Initial deploy',
    items: [
      'BLW Content Hub goes live on Vercel with full team/player/stats surface.',
      '404 routing fix for direct deep-links.',
      'Brand alignment design overhaul — hybrid theme, BLW palette, fonts.',
    ],
  },
];

// Auto-derived from the top entry so version.js doesn't have to be
// kept in sync separately. Bumping a release here updates every
// surface that reads CURRENT_VERSION.
export const CURRENT_VERSION = RELEASES[0].version;
export const CURRENT_RELEASE = RELEASES[0];

// Color tokens for the kind chip in the changelog modal. Major =
// red (the BLW accent), minor = blue (cool but present), patch =
// muted (background work). Matches the visual cadence of the
// dashboard's status chips so the modal feels native.
export const KIND_TOKENS = {
  major: { bg: 'rgba(220,38,38,0.10)', border: 'rgba(220,38,38,0.30)', fg: '#B91C1C', label: 'MAJOR' },
  minor: { bg: 'rgba(59,130,246,0.10)', border: 'rgba(59,130,246,0.30)', fg: '#1D4ED8', label: 'MINOR' },
  patch: { bg: 'rgba(107,114,128,0.10)', border: 'rgba(107,114,128,0.30)', fg: '#374151', label: 'PATCH' },
};
